services:
    qdrant:
        image: qdrant/qdrant:v1.12.5
        restart: unless-stopped
        volumes:
            - ./data/qdrant:/qdrant/storage:z
        expose:
            - 6333
    client:
        image: superdapp/eliza:latest
        restart: unless-stopped
        depends_on:
            - server
        stdin_open: true
        tty: true
        command: ["pnpm", "start:client", "--host"]
        env_file:
          - .env
        expose:
          - 5173
    server:
        image: superdapp/eliza:latest
        restart: unless-stopped
        mem_limit: 8g
        mem_reservation: 2g
        depends_on:
            - qdrant
        stdin_open: true
        tty: true
        build:
            context: .
            dockerfile: Dockerfile
#        deploy:
#          resources:
#            reservations:
#              devices:
#                - driver: nvidia
#                  count: 1
#                  capabilities: [gpu]
        volumes:
            - ./data/tweetcache:/app/packages/client-twitter/src/tweetcache
            - ./data/agent:/app/agent/data/
        command: ["pnpm", "start", "--character=characters/aida.character.json"]
        env_file:
            - .env
        expose:
            - 3000

